name: build and push doc to S3
on:
  pull_request:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker pull squidfunk/mkdocs-material
          docker run --rm -i -v ${PWD}/docs:/docs squidfunk/mkdocs-material build
    # - name: Set up AWS CLI
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y awscli

    # - name: Upload file to Scaleway Object Storage
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
    #   run: |
    #     aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
    #     aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    #     aws configure set region nl-ams

    #     aws s3 cp --recursive ./docs/site/ s3://$BUCKET_NAME --endpoint-url https://s3.nl-ams.scw.cloud
      - name: Install MinIO Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc --help
      - name: Create MinIO alias
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          ./mc alias set scws3 https://s3.nl-ams.scw.cloud $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
      - name: Push to bucket
        run: |
          ./mc cp --recursive ./docs/site/ scws3/scaleway-cli-doc/