name: build and push doc to S3
on:
  pull_request:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - uses: actions/checkout@v4
      - name: prepare temporary folder for build
        run: |
          cd docs
          mkdir docs
          ls
          cp commands/* docs/
          cp -r static_files/* docs/
      - name: Pull Material for MKdocs image and build doc
        run: |
          docker pull squidfunk/mkdocs-material
          docker run --rm -i -v ${PWD}/docs:/docs squidfunk/mkdocs-material build
      - name: Install MinIO Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc --help
      - name: Create MinIO alias
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        run: |
          ./mc alias set scws3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
      - name: Push to bucket
        run: |
          ./mc cp --recursive ./docs/site/ scws3/$BUCKET_NAME
      - name: Delete temporary folder
        run: rm -rf docs/docs/