
name: build and push doc to S3
on:
  pull_request:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials # stolen from material for MKdocs action to push to GH pages
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: cd docs && mkdocs build
      - name: Install MinIO Client # works, but insufficient rights to copy to bucket
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc --help
      - name: Create MinIO alias
        run: |
          ./mc alias set scws3 https://s3.fr-par.scw.cloud ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} --api S3v4
      - name: Push to bucket
        run: |
          ./mc cp --debug --recursive ./docs/site/ scws3/test-actions-doc/
      - run: rm -rf ./docs/site