
# on:
#   pull_request:

# jobs:
#   build_docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Setup material for MKdocs
#         run: |
#           cd docs && mkdocs build
  
#   push_docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#       - name: Setup AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: fr-par
#       - name: Push to bucket
#         run: |
#         aws s3 sync ./docs/site https://test-actions-doc.s3.fr-par.scw.cloud


name: build and push doc to S3
on:
  pull_request:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: ls
      - run: cd docs && mkdocs build
      - run: ls
      - name: Install MinIO Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc --help
      - name: Create MinIO alias
        run: |
          sudo mc alias set scws3 https://s3.fr-par.scw.cloud \ 
          ${{ secrets.AWS_ACCESS_KEY_ID }} \
          ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --api S3v4
      - name: Push to bucket
        run: |
          sudo mc cp --recursive ./docs/site/ scws3/test-actions-doc/
      - run: rm -rf ./docs/site